export const skillOptions = [
  "Web Development",
  "Mobile Development",
  "UI/UX Design",
  "Graphic Design",
  "Marketing",
  "Content Writing",
  "SEO",
  "Social Media",
  "Business Strategy",
  "Product Management",
  "Data Analysis",
  "AI/ML",
  "DevOps",
  "Sales",
  "Customer Support",
  "Video Editing",
  "Audio Production",
  "Photography",
  "Illustration",
  "Animation",
  "3D Modeling",
  "Game Development",
  "Blockchain",
  "Copywriting",
  "Email Marketing",
];

// Collaboration term options for future use
export const collaborationTermOptions = [
  "Revenue Share",
  "Equity",
  "Fixed Fee",
  "Hourly Rate",
  "Skill Exchange",
  "Co-founder",
  "Advisor",
  "Mentorship",
];
